version: 2

models:
  # 1. Customers
  - name: customers
    description: "ตารางเก็บข้อมูลลูกค้าที่ Clean แล้ว (1 แถว ต่อ 1 customer_pk)"
    columns:
      - name: customer_pk
        description: "PK (Surrogate Key) สร้างจาก MD5(customer_id)"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Natural Key (จาก staging), 1 ID ต่อ 1 ออเดอร์"
        tests:
          - unique
          - not_null
      - name: customer_unique_id
        description: "ID ที่แท้จริงของลูกค้า (1 คน อาจมีหลาย customer_id)"
        tests:
          - not_null
      - name: customer_zip_code_prefix
      - name: customer_city
      - name: customer_state

  # 2. Orders
  - name: orders
    description: "ตารางเก็บข้อมูลออเดอร์หลัก (1 แถว ต่อ 1 order_pk)"
    columns:
      - name: order_pk
        description: "PK (Surrogate Key) สร้างจาก MD5(order_id)"
        tests:
          - unique
          - not_null
      - name: order_id
        description: "Natural Key ของออเดอร์"
        tests:
          - unique
          - not_null
      - name: customer_id 
        description: "Natural Key (จาก staging) สำหรับเชื่อมโยงข้อมูลเก่า"
        tests:
          - not_null
      - name: order_status
        description: "สถานะของออเดอร์"
        tests:
          - not_null
          - accepted_values:
              values: ['delivered', 'shipped', 'invoiced', 'processing', 'created', 'canceled', 'unavailable', 'approved']
      - name: order_purchase_timestamp
      - name: order_approved_at
      - name: order_delivered_carrier_date
      - name: order_delivered_customer_date
      - name: order_estimated_delivery_date

  # 3. Products
  - name: product
    description: "ตารางเก็บข้อมูลสินค้าที่ Clean แล้ว (1 แถว ต่อ 1 product_pk)"
    columns:
      - name: product_pk
        description: "PK (Surrogate Key) สร้างจาก MD5(product_id)"
        tests:
          - unique
          - not_null
      - name: product_id
        description: "Natural Key ของสินค้า"
        tests:
          - unique
          - not_null
      - name: product_category_name
        description: "Natural Key (จาก staging)"
      - name: product_name_length
      - name: product_description_length
      - name: product_photos_qty
      - name: product_weight_g
        description: "น้ำหนักสินค้า (กรัม) ต้องไม่ติดลบ"
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"
      - name: product_length_cm
      - name: product_height_cm
      - name: product_width_cm

  # 4. Sellers
  - name: sellers
    description: "ตารางเก็บข้อมูลผู้ขาย (1 แถว ต่อ 1 seller_pk)"
    columns:
      - name: seller_pk
        description: "PK (Surrogate Key) สร้างจาก MD5(seller_id)"
        tests:
          - unique
          - not_null
      - name: seller_id
        description: "Natural Key ของผู้ขาย"
        tests:
          - unique
          - not_null
      - name: seller_zip_code_prefix
      - name: seller_city
      - name: seller_state

  # 5. Order Items
  - name: order_items
    description: "ตารางเก็บรายการสินค้าในแต่ละออเดอร์ (Grain: order_item_pk)"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - order_id
            - order_item_id
    columns:
      - name: order_item_pk
        description: "PK (Surrogate Key) สร้างจาก MD5(order_id || order_item_id)"
        tests:
          - unique
          - not_null
      - name: order_id
        description: "Natural Key (จาก staging)"
        tests:
          - not_null
      - name: order_item_id
        description: "ลำดับของสินค้าในออเดอร์"
        tests:
          - not_null
      - name: product_id
        description: "Natural Key (จาก staging)"
        tests:
          - not_null
      - name: seller_id
        description: "Natural Key (จาก staging)"
        tests:
          - not_null
      - name: shipping_limit_date
      - name: price
      - name: freight_value

  # 6. Order Payments
  - name: order_payment
    description: "ตารางเก็บข้อมูลการชำระเงิน (Grain: order_payment_pk)"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - order_id
            - payment_sequential
    columns:
      - name: order_payment_pk
        description: "PK (Surrogate Key) สร้างจาก MD5(order_id || payment_sequential)"
        tests:
          - unique
          - not_null
      - name: order_id
        description: "Natural Key (จาก staging)"
        tests:
          - not_null
      - name: payment_sequential
      - name: payment_type
      - name: payment_installments
      - name: payment_value

  # 7. Order Reviews
  - name: order_reviews
    description: "ตารางเก็บรีวิว (Grain: review_pk)"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - review_id
            - order_id
    columns:
      - name: review_pk
        description: "PK (Surrogate Key) สร้างจาก MD5(review_id)"
        tests:
          - unique
          - not_null
      - name: review_id
        description: "Natural Key ของรีวิว (หลังจาก deduplicate)"
        tests:
          - unique
          - not_null
      - name: order_id
        description: "Natural Key (จาก staging)"
        tests:
          - not_null
      - name: review_score
        description: "คะแนนรีวิวต้องอยู่ระหว่าง 1 ถึง 5"
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4, 5]
      - name: review_comment_title
      - name: review_comment_message
      - name: review_creation_date
      - name: review_answer_timestamp

  # 8. Geolocation
  - name: geolocation
    description: "ตารางข้อมูลพิกัด (ข้อมูลอาจซ้ำได้ใน Layer นี้)"
    columns:
      - name: geolocation_zip_code_prefix
        description: "รหัสไปรษณีย์ (ยังไม่ unique ใน layer นี้)"
        tests:
          - not_null
      - name: geolocation_lat
      - name: geolocation_lng
      - name: geolocation_city
      - name: geolocation_state

  # 9. Product Category Translation
  - name: product_category_translation
    description: "ตารางแปลชื่อหมวดหมู่สินค้า (Grain: product_category_pk)"
    columns:
      - name: product_category_pk
        description: "PK (Surrogate Key) สร้างจาก MD5(product_category_name)"
        tests:
          - unique
          - not_null
      - name: product_category_name
        description: "Natural Key ชื่อหมวดหมู่ภาษาโปรตุเกส"
        tests:
          - unique
          - not_null
      - name: product_category_name_english
        description: "ชื่อหมวดหมู่ภาษาอังกฤษ"
        tests:
          - not_null